export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  PROMPT_ADD_NEW : "PROMPT_ADD_NEW",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
}

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
}

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  PROMPT_DELETE: "PROMPT_DELETE",
}
