export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
}

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
}

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  LEAD_DELETE: "LEAD_DELETE",
}
